language: dart

dart:
  - stable

dart_task:
  - test
  - dartfmt
  - dartanalyzer

# Only building main means that we don't run two builds for each pull request.
branches:
  only: [main]

cache:
  directories:
    - $HOME/.pub-cache
