language: dart

dart:
  #  - 2.10.0
  # Disabling stable for now since we rely on a null safety version of test.
  - dev

dart_task:
  - test
  - dartfmt
  - dartanalyzer

# Only building main means that we don't run two builds for each pull request.
branches:
  only: [main]

cache:
  directories:
    - $HOME/.pub-cache
