name: uhst
version: 2.0.0

description: UHST client for Flutter

homepage: https://github.com/uhst/uhst-client-flutter
environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.0.4
  # universal_io: ^1.0.2
  http: ^0.13.0

dev_dependencies:
  # https://pub.dev/packages/test
  test: ^1.16.8
  # https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md
  # mockito: ^5.0.0-nullsafety.2
